import pandas as pd
import openpyxl
import xlrd


# test comment
# see if changes are committed to main 
VOTING_TENDENCIES = {
    2020: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Democratic',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2019: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Democratic',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2018: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Democratic',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2017: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Democratic',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2016: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Republican',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Republican',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Republican',
        'Wyoming': 'Republican'
    },
    2015: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Republican',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Republican',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Republican',
        'Wyoming': 'Republican'
    },
    2014: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Republican',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Republican',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Republican',
        'Wyoming': 'Republican'
    },
    2013: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Republican',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Republican',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Republican',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Republican',
        'Wyoming': 'Republican'
    },
    2012: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2011: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2010: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2009: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Republican',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2008: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Democratic',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2007: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Democratic',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2006: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Democratic',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2005: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Democratic',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Democratic',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Democratic',
        'North Dakota': 'Republican',
        'Ohio': 'Democratic',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2004: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Republican',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2003: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Republican',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2002: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Republican',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2001: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Republican',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    },
    2000: {
        'Alabama': 'Republican',
        'Alaska': 'Republican',
        'Arizona': 'Republican',
        'Arkansas': 'Democratic',
        'California': 'Democratic',
        'Colorado': 'Republican',
        'Connecticut': 'Democratic',
        'Delaware': 'Democratic',
        'Florida': 'Republican',
        'Georgia': 'Republican',
        'Hawaii': 'Democratic',
        'Idaho': 'Republican',
        'Illinois': 'Democratic',
        'Indiana': 'Republican',
        'Iowa': 'Democratic',
        'Kansas': 'Republican',
        'Kentucky': 'Republican',
        'Louisiana': 'Republican',
        'Maine': 'Democratic',
        'Maryland': 'Democratic',
        'Massachusetts': 'Democratic',
        'Michigan': 'Democratic',
        'Minnesota': 'Democratic',
        'Mississippi': 'Republican',
        'Missouri': 'Republican',
        'Montana': 'Republican',
        'Nebraska': 'Republican',
        'Nevada': 'Democratic',
        'New Hampshire': 'Democratic',
        'New Jersey': 'Democratic',
        'New Mexico': 'Democratic',
        'New York': 'Democratic',
        'North Carolina': 'Republican',
        'North Dakota': 'Republican',
        'Ohio': 'Republican',
        'Oklahoma': 'Republican',
        'Oregon': 'Democratic',
        'Pennsylvania': 'Democratic',
        'Rhode Island': 'Democratic',
        'South Carolina': 'Republican',
        'South Dakota': 'Republican',
        'Tennessee': 'Republican',
        'Texas': 'Republican',
        'Utah': 'Republican',
        'Vermont': 'Democratic',
        'Virginia': 'Democratic',
        'Washington': 'Democratic',
        'West Virginia': 'Republican',
        'Wisconsin': 'Democratic',
        'Wyoming': 'Republican'
    }
}




def get_file_name(year):
    if 2000 <= year <= 2006:
        return "inflow2000to2006.xls"
    elif 2007 <= year <= 2012:
        return "inflow2007to2012.xls"
    elif 2013 <= year <= 2017:
        return "inflow2013to2017.xlsx"
    elif 2018 <= year <= 2020:
        return "inflow2016to2020.xlsx"
    else:
        raise ValueError("Year must be between 2000 and 2020.")

def read_excel_file(file_name):
    if file_name.endswith('.xls'):
        return pd.read_excel(file_name, engine='xlrd')
    elif file_name.endswith('.xlsx'):
        return pd.read_excel(file_name, engine='openpyxl')
    else:
        raise ValueError("Unsupported file format. Only .xls and .xlsx are supported.")

def get_state_political_affiliation(state, year):
    if year in VOTING_TENDENCIES and state in VOTING_TENDENCIES[year]:
        return VOTING_TENDENCIES[year][state]
    else:
        raise ValueError(f"Political affiliation for {state} in {year} not found.")

def immigration(year, state):
    file_name = get_file_name(year)

    dfs = read_excel_file(file_name)

    county_data = {}

    for sheet_name, df in dfs.items():
        filtered_df = df[df['State/U.S. Island Area/Foreign Region of Residence 1 Year Ago'] == state]

        for _, row in filtered_df.iterrows():
            state_of_origin = row['State/U.S. Island Area/Foreign Region of Residence 1 Year Ago']
            county_name = row['County of Current Residence'].strip()  # County name as a string

            affiliation = get_state_political_affiliation(state_of_origin, year)

            if affiliation:
                if county_name not in county_data:
                    county_data[county_name] = {'blue': 0, 'red': 0}

                if affiliation == 'Democrat':
                    county_data[county_name]['blue'] += 1
                elif affiliation == 'Republican':
                    county_data[county_name]['red'] += 1

    for county, counts in county_data.items():
        print(f"{county}_blue_balls: {counts['blue']}")
        print(f"{county}_red_balls: {counts['red']}")

# For example, calling the function with year 2006 and state Alabama
immigration(2004, 'Alabama')
